# Generated by Django 2.2.5 on 2023-03-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcc_app', '0002_auto_20230311_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
