# Generated by Django 2.2.5 on 2023-03-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcc_app', '0004_breastcancerresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breastcancerresult',
            name='area_se',
        ),
        migrations.RemoveField(
            model_name='breastcancerresult',
            name='compactness_mean',
        ),
        migrations.RemoveField(
            model_name='breastcancerresult',
            name='compactness_worst',
        ),
        migrations.RemoveField(
            model_name='breastcancerresult',
            name='perimeter_se',
        ),
        migrations.RemoveField(
            model_name='breastcancerresult',
            name='radius_se',
        ),
    ]
