# Generated by Django 2.2.5 on 2023-03-25 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcc_app', '0005_auto_20230325_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='LungCancerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_pollution', models.FloatField()),
                ('alcohol_use', models.CharField(max_length=50)),
                ('dust_allergy1', models.CharField(max_length=50)),
                ('dust_allergy2', models.FloatField()),
                ('occupational_hazard1', models.CharField(max_length=50)),
                ('occupational_hazard2', models.CharField(max_length=50)),
                ('genetic_risk', models.CharField(max_length=50)),
                ('chronic_lung_disease', models.CharField(max_length=50)),
                ('balanced_diet', models.FloatField()),
                ('obesity', models.FloatField()),
                ('passive_smoker', models.CharField(max_length=50)),
                ('chest_pain1', models.CharField(max_length=50)),
                ('chest_pain2', models.FloatField()),
                ('coughing_blood', models.CharField(max_length=50)),
                ('fatigue', models.CharField(max_length=50)),
                ('prediction', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LungCancerResult',
            },
        ),
    ]
