# Generated by Django 2.2.5 on 2023-03-26 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vcc_app', '0006_lungcancerresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungcancerresult',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
