# Generated by Django 2.2.5 on 2023-03-26 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcc_app', '0007_lungcancerresult_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeukemiaCancerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sv', models.FloatField()),
                ('prediction', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LeukemiaCancerResult',
            },
        ),
    ]
