# Generated by Django 2.2.5 on 2023-03-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcc_app', '0008_leukemiacancerresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breastcancerresult',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='leukemiacancerresult',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
